package com.smartcity.models;

import org.apache.ibatis.type.Alias;

@Alias("api")
public class API {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.idAPI
     *
     * @mbggenerated
     */
    private Integer idapi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.serverid
     *
     * @mbggenerated
     */
    private Integer serverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.packagedAPI
     *
     * @mbggenerated
     */
    private String packagedapi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.originalAPI
     *
     * @mbggenerated
     */
    private String originalapi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api.returnData
     *
     * @mbggenerated
     */
    private String returndata;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public API(Integer idapi, Integer serverid, String packagedapi, String originalapi, String returndata) {
        this.idapi = idapi;
        this.serverid = serverid;
        this.packagedapi = packagedapi;
        this.originalapi = originalapi;
        this.returndata = returndata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    public API() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.idAPI
     *
     * @return the value of api.idAPI
     *
     * @mbggenerated
     */
    public Integer getIdapi() {
        return idapi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.idAPI
     *
     * @param idapi the value for api.idAPI
     *
     * @mbggenerated
     */
    public void setIdapi(Integer idapi) {
        this.idapi = idapi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.serverid
     *
     * @return the value of api.serverid
     *
     * @mbggenerated
     */
    public Integer getServerid() {
        return serverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.serverid
     *
     * @param serverid the value for api.serverid
     *
     * @mbggenerated
     */
    public void setServerid(Integer serverid) {
        this.serverid = serverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.packagedAPI
     *
     * @return the value of api.packagedAPI
     *
     * @mbggenerated
     */
    public String getPackagedapi() {
        return packagedapi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.packagedAPI
     *
     * @param packagedapi the value for api.packagedAPI
     *
     * @mbggenerated
     */
    public void setPackagedapi(String packagedapi) {
        this.packagedapi = packagedapi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.originalAPI
     *
     * @return the value of api.originalAPI
     *
     * @mbggenerated
     */
    public String getOriginalapi() {
        return originalapi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.originalAPI
     *
     * @param originalapi the value for api.originalAPI
     *
     * @mbggenerated
     */
    public void setOriginalapi(String originalapi) {
        this.originalapi = originalapi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api.returnData
     *
     * @return the value of api.returnData
     *
     * @mbggenerated
     */
    public String getReturndata() {
        return returndata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api.returnData
     *
     * @param returndata the value for api.returnData
     *
     * @mbggenerated
     */
    public void setReturndata(String returndata) {
        this.returndata = returndata;
    }
}