package com.smartcity.models;

import org.springframework.stereotype.Repository;

@Repository
public class ApplicationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APPID
     *
     * @mbggenerated
     */
    private Integer appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.DeveloperID
     *
     * @mbggenerated
     */
    private String developerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public ApplicationKey(Integer appid, String developerid) {
        this.appid = appid;
        this.developerid = developerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public ApplicationKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APPID
     *
     * @return the value of application.APPID
     *
     * @mbggenerated
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APPID
     *
     * @param appid the value for application.APPID
     *
     * @mbggenerated
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.DeveloperID
     *
     * @return the value of application.DeveloperID
     *
     * @mbggenerated
     */
    public String getDeveloperid() {
        return developerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.DeveloperID
     *
     * @param developerid the value for application.DeveloperID
     *
     * @mbggenerated
     */
    public void setDeveloperid(String developerid) {
        this.developerid = developerid;
    }
}