package com.smartcity.models;

import org.springframework.stereotype.Repository;

@Repository
public class Application extends ApplicationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.APPName
     *
     * @mbggenerated
     */
    private String appname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.Categary
     *
     * @mbggenerated
     */
    private String categary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.Logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.Tags
     *
     * @mbggenerated
     */
    private String tags;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public Application(Integer appid, String developerid, String appname, String url, String categary, String description, String logo, String tags) {
        super(appid, developerid);
        this.appname = appname;
        this.url = url;
        this.categary = categary;
        this.description = description;
        this.logo = logo;
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    public Application() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.APPName
     *
     * @return the value of application.APPName
     *
     * @mbggenerated
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.APPName
     *
     * @param appname the value for application.APPName
     *
     * @mbggenerated
     */
    public void setAppname(String appname) {
        this.appname = appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.URL
     *
     * @return the value of application.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.URL
     *
     * @param url the value for application.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.Categary
     *
     * @return the value of application.Categary
     *
     * @mbggenerated
     */
    public String getCategary() {
        return categary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.Categary
     *
     * @param categary the value for application.Categary
     *
     * @mbggenerated
     */
    public void setCategary(String categary) {
        this.categary = categary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.Description
     *
     * @return the value of application.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.Description
     *
     * @param description the value for application.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.Logo
     *
     * @return the value of application.Logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.Logo
     *
     * @param logo the value for application.Logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.Tags
     *
     * @return the value of application.Tags
     *
     * @mbggenerated
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.Tags
     *
     * @param tags the value for application.Tags
     *
     * @mbggenerated
     */
    public void setTags(String tags) {
        this.tags = tags;
    }
}