package com.smartcity.models;

import org.springframework.stereotype.Repository;

@Repository
public class Developer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.DeveloperID
     *
     * @mbggenerated
     */
    private String developerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column developer.User_UUID
     *
     * @mbggenerated
     */
    private String userUuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbggenerated
     */
    public Developer(String developerid, String userUuid) {
        this.developerid = developerid;
        this.userUuid = userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbggenerated
     */
    public Developer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.DeveloperID
     *
     * @return the value of developer.DeveloperID
     *
     * @mbggenerated
     */
    public String getDeveloperid() {
        return developerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.DeveloperID
     *
     * @param developerid the value for developer.DeveloperID
     *
     * @mbggenerated
     */
    public void setDeveloperid(String developerid) {
        this.developerid = developerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column developer.User_UUID
     *
     * @return the value of developer.User_UUID
     *
     * @mbggenerated
     */
    public String getUserUuid() {
        return userUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column developer.User_UUID
     *
     * @param userUuid the value for developer.User_UUID
     *
     * @mbggenerated
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid;
    }
}