package com.smartcity.models;

import org.springframework.stereotype.Repository;

@Repository
public class InterfaceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.InterfaceID
     *
     * @mbggenerated
     */
    private Integer interfaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.APPID
     *
     * @mbggenerated
     */
    private Integer appid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    public InterfaceKey(Integer interfaceid, Integer appid) {
        this.interfaceid = interfaceid;
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    public InterfaceKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.InterfaceID
     *
     * @return the value of interface.InterfaceID
     *
     * @mbggenerated
     */
    public Integer getInterfaceid() {
        return interfaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.InterfaceID
     *
     * @param interfaceid the value for interface.InterfaceID
     *
     * @mbggenerated
     */
    public void setInterfaceid(Integer interfaceid) {
        this.interfaceid = interfaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.APPID
     *
     * @return the value of interface.APPID
     *
     * @mbggenerated
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.APPID
     *
     * @param appid the value for interface.APPID
     *
     * @mbggenerated
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }
}