package com.smartcity.models;

import org.springframework.stereotype.Repository;

@Repository
public class Interface extends InterfaceKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.DataAddr
     *
     * @mbggenerated
     */
    private String dataaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.Method
     *
     * @mbggenerated
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.Parameters
     *
     * @mbggenerated
     */
    private String parameters;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    public Interface(Integer interfaceid, Integer appid, String dataaddr, String method, String parameters) {
        super(interfaceid, appid);
        this.dataaddr = dataaddr;
        this.method = method;
        this.parameters = parameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    public Interface() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.DataAddr
     *
     * @return the value of interface.DataAddr
     *
     * @mbggenerated
     */
    public String getDataaddr() {
        return dataaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.DataAddr
     *
     * @param dataaddr the value for interface.DataAddr
     *
     * @mbggenerated
     */
    public void setDataaddr(String dataaddr) {
        this.dataaddr = dataaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.Method
     *
     * @return the value of interface.Method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.Method
     *
     * @param method the value for interface.Method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.Parameters
     *
     * @return the value of interface.Parameters
     *
     * @mbggenerated
     */
    public String getParameters() {
        return parameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.Parameters
     *
     * @param parameters the value for interface.Parameters
     *
     * @mbggenerated
     */
    public void setParameters(String parameters) {
        this.parameters = parameters;
    }
}