package com.smartcity.models;

public class Interface {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.InterfaceID
     *
     * @mbggenerated
     */
    private Integer interfaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.DataAddr
     *
     * @mbggenerated
     */
    private String dataaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.Method
     *
     * @mbggenerated
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.Parameters
     *
     * @mbggenerated
     */
    private String parameters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interface.APPID
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    public Interface(Integer interfaceid, String dataaddr, String method, String parameters, String appid) {
        this.interfaceid = interfaceid;
        this.dataaddr = dataaddr;
        this.method = method;
        this.parameters = parameters;
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    public Interface() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.InterfaceID
     *
     * @return the value of interface.InterfaceID
     *
     * @mbggenerated
     */
    public Integer getInterfaceid() {
        return interfaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.InterfaceID
     *
     * @param interfaceid the value for interface.InterfaceID
     *
     * @mbggenerated
     */
    public void setInterfaceid(Integer interfaceid) {
        this.interfaceid = interfaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.DataAddr
     *
     * @return the value of interface.DataAddr
     *
     * @mbggenerated
     */
    public String getDataaddr() {
        return dataaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.DataAddr
     *
     * @param dataaddr the value for interface.DataAddr
     *
     * @mbggenerated
     */
    public void setDataaddr(String dataaddr) {
        this.dataaddr = dataaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.Method
     *
     * @return the value of interface.Method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.Method
     *
     * @param method the value for interface.Method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.Parameters
     *
     * @return the value of interface.Parameters
     *
     * @mbggenerated
     */
    public String getParameters() {
        return parameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.Parameters
     *
     * @param parameters the value for interface.Parameters
     *
     * @mbggenerated
     */
    public void setParameters(String parameters) {
        this.parameters = parameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interface.APPID
     *
     * @return the value of interface.APPID
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interface.APPID
     *
     * @param appid the value for interface.APPID
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }
}