package com.smartcity.models;

import org.springframework.stereotype.Repository;

@Repository
public class Server {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers.serverid
     *
     * @mbggenerated
     */
    private Integer serverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers.servername
     *
     * @mbggenerated
     */
    private String servername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column servers.connectStatus
     *
     * @mbggenerated
     */
    private String connectstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbggenerated
     */
    public Server(Integer serverid, String servername, String connectstatus) {
        this.serverid = serverid;
        this.servername = servername;
        this.connectstatus = connectstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbggenerated
     */
    public Server() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers.serverid
     *
     * @return the value of servers.serverid
     *
     * @mbggenerated
     */
    public Integer getServerid() {
        return serverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers.serverid
     *
     * @param serverid the value for servers.serverid
     *
     * @mbggenerated
     */
    public void setServerid(Integer serverid) {
        this.serverid = serverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers.servername
     *
     * @return the value of servers.servername
     *
     * @mbggenerated
     */
    public String getServername() {
        return servername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers.servername
     *
     * @param servername the value for servers.servername
     *
     * @mbggenerated
     */
    public void setServername(String servername) {
        this.servername = servername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column servers.connectStatus
     *
     * @return the value of servers.connectStatus
     *
     * @mbggenerated
     */
    public String getConnectstatus() {
        return connectstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column servers.connectStatus
     *
     * @param connectstatus the value for servers.connectStatus
     *
     * @mbggenerated
     */
    public void setConnectstatus(String connectstatus) {
        this.connectstatus = connectstatus;
    }
}