package com.smartcity.dao;

import com.smartcity.models.API;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Transactional
@Service(value="apiMapper")
public interface APIMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    @Delete({
        "delete from api",
        "where idAPI = #{idapi,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer idapi);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    @Insert({
        "insert into api (idAPI, serverid, ",
        "packagedAPI, originalAPI, ",
        "returnData)",
        "values (#{idapi,jdbcType=INTEGER}, #{serverid,jdbcType=INTEGER}, ",
        "#{packagedapi,jdbcType=VARCHAR}, #{originalapi,jdbcType=VARCHAR}, ",
        "#{returndata,jdbcType=VARCHAR})"
    })
    int insert(API record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    int insertSelective(API record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "idAPI, serverid, packagedAPI, originalAPI, returnData",
        "from api",
        "where idAPI = #{idapi,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    API selectByPrimaryKey(Integer idapi);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(API record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api
     *
     * @mbggenerated
     */
    @Update({
        "update api",
        "set serverid = #{serverid,jdbcType=INTEGER},",
          "packagedAPI = #{packagedapi,jdbcType=VARCHAR},",
          "originalAPI = #{originalapi,jdbcType=VARCHAR},",
          "returnData = #{returndata,jdbcType=VARCHAR}",
        "where idAPI = #{idapi,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(API record);

    List<API> findAll();
}