package com.smartcity.dao;

import com.smartcity.models.Application;
import com.smartcity.models.ApplicationKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    @Delete({
        "delete from application",
        "where APPID = #{appid,jdbcType=INTEGER}",
          "and DeveloperID = #{developerid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(ApplicationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    @Insert({
        "insert into application (APPID, DeveloperID, ",
        "APPName, URL, Categary, ",
        "Description, Logo, ",
        "Tags)",
        "values (#{appid,jdbcType=INTEGER}, #{developerid,jdbcType=VARCHAR}, ",
        "#{appname,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, #{categary,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{logo,jdbcType=VARCHAR}, ",
        "#{tags,jdbcType=VARCHAR})"
    })
    int insert(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    int insertSelective(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "APPID, DeveloperID, APPName, URL, Categary, Description, Logo, Tags",
        "from application",
        "where APPID = #{appid,jdbcType=INTEGER}",
          "and DeveloperID = #{developerid,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Application selectByPrimaryKey(ApplicationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table application
     *
     * @mbggenerated
     */
    @Update({
        "update application",
        "set APPName = #{appname,jdbcType=VARCHAR},",
          "URL = #{url,jdbcType=VARCHAR},",
          "Categary = #{categary,jdbcType=VARCHAR},",
          "Description = #{description,jdbcType=VARCHAR},",
          "Logo = #{logo,jdbcType=VARCHAR},",
          "Tags = #{tags,jdbcType=VARCHAR}",
        "where APPID = #{appid,jdbcType=INTEGER}",
          "and DeveloperID = #{developerid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Application record);
}