package com.smartcity.dao;

import com.smartcity.models.Developer;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.springframework.stereotype.Repository;

@Repository
public interface DeveloperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbggenerated
     */
    @Delete({
        "delete from developer",
        "where DeveloperID = #{developerid,jdbcType=VARCHAR}",
          "and User_UUID = #{userUuid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(Developer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbggenerated
     */
    @Insert({
        "insert into developer (DeveloperID, User_UUID)",
        "values (#{developerid,jdbcType=VARCHAR}, #{userUuid,jdbcType=VARCHAR})"
    })
    int insert(Developer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table developer
     *
     * @mbggenerated
     */
    int insertSelective(Developer record);
    Developer findDevByUUID(String UUID);
    String findDevIDByUUID(String UUID);

}