package com.smartcity.dao;

import com.smartcity.models.Interface;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

@Repository
public interface InterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    @Delete({
        "delete from interface",
        "where InterfaceID = #{interfaceid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer interfaceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    @Insert({
        "insert into interface (InterfaceID, DataAddr, ",
        "Method, Parameters, ",
        "APPID)",
        "values (#{interfaceid,jdbcType=INTEGER}, #{dataaddr,jdbcType=VARCHAR}, ",
        "#{method,jdbcType=VARCHAR}, #{parameters,jdbcType=VARCHAR}, ",
        "#{appid,jdbcType=VARCHAR})"
    })
    int insert(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    int insertSelective(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "InterfaceID, DataAddr, Method, Parameters, APPID",
        "from interface",
        "where InterfaceID = #{interfaceid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Interface selectByPrimaryKey(Integer interfaceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Interface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface
     *
     * @mbggenerated
     */
    @Update({
        "update interface",
        "set DataAddr = #{dataaddr,jdbcType=VARCHAR},",
          "Method = #{method,jdbcType=VARCHAR},",
          "Parameters = #{parameters,jdbcType=VARCHAR},",
          "APPID = #{appid,jdbcType=VARCHAR}",
        "where InterfaceID = #{interfaceid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Interface record);
    Interface findInterfaceByAddrMethod(String addr,String method);
}