package com.smartcity.dao;

import com.smartcity.models.User;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Repository;

@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user",
        "where PrivateID = #{privateid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer privateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user (PrivateID, UUID, ",
        "IDCardNumber, UserName, ",
        "PhoneNum, Password, ",
        "Sex, Attachment)",
        "values (#{privateid,jdbcType=INTEGER}, #{uuid,jdbcType=VARCHAR}, ",
        "#{idcardnumber,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, ",
        "#{phonenum,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=VARCHAR}, #{attachment,jdbcType=VARCHAR})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "PrivateID, UUID, IDCardNumber, UserName, PhoneNum, Password, Sex, Attachment",
        "from user",
        "where PrivateID = #{privateid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    User selectByPrimaryKey(Integer privateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Update({
        "update user",
        "set UUID = #{uuid,jdbcType=VARCHAR},",
          "IDCardNumber = #{idcardnumber,jdbcType=VARCHAR},",
          "UserName = #{username,jdbcType=VARCHAR},",
          "PhoneNum = #{phonenum,jdbcType=VARCHAR},",
          "Password = #{password,jdbcType=VARCHAR},",
          "Sex = #{sex,jdbcType=VARCHAR},",
          "Attachment = #{attachment,jdbcType=VARCHAR}",
        "where PrivateID = #{privateid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(User record);
    User findByPhoneNum(String phoneNum);
    int findByUUID(String UUID);//返回primarykey privateID

}